junction.exe 1_Propulsion\CurrentSoftware\project_2012\QS QS
junction.exe 2_Strategie\CurrentSoftware\QS QS
junction.exe 3_Actionneur\CurrentSoftware\QS QS
junction.exe 4_Balises\Software_Emetteur_US\QS QS
junction.exe 4_Balises\Software_Mere\QS QS
junction.exe 4_Balises\Software_Recepteur_IR\Project\QS QS
junction.exe 4_Balises\Software_Recepteur_US\QS QS
junction.exe 5_Supervision\Current_Software\QS QS
junction.exe 5_Supervision\SD_Project\QS QS
