/*
 *  Club Robot ESEO 2008 - 2014
 *
 *  $Id$
 *
 *  Package : Carte Actionneur
 *  Description : Définition de types pour les variables globales
				définies specifiquement pour ce code.
 *  Auteur : Jacen
 */

typedef enum {
	QUEUE_ACT_RX24_ORE_GUN,
    QUEUE_ACT_AX12_BIG_BALL_BACK_LEFT,
    QUEUE_ACT_AX12_BIG_BALL_BACK_RIGHT,
    QUEUE_ACT_AX12_BIG_BALL_FRONT_LEFT,
    QUEUE_ACT_AX12_BIG_BALL_FRONT_RIGHT,
	QUEUE_ACT_AX12_CYLINDER_SLOPE_LEFT,
	QUEUE_ACT_AX12_CYLINDER_SLOPE_RIGHT,
	QUEUE_ACT_AX12_CYLINDER_BALANCER_LEFT,
	QUEUE_ACT_AX12_CYLINDER_BALANCER_RIGHT,
    QUEUE_ACT_AX12_BEARING_BALL_WHEEL,
    QUEUE_ACT_AX12_CYLINDER_PUSHER_LEFT,
    QUEUE_ACT_AX12_CYLINDER_PUSHER_RIGHT,
    QUEUE_ACT_RX24_CYLINDER_ELEVATOR_LEFT,
    QUEUE_ACT_RX24_CYLINDER_ELEVATOR_RIGHT,
    QUEUE_ACT_RX24_CYLINDER_SLIDER_LEFT,
    QUEUE_ACT_RX24_CYLINDER_SLIDER_RIGHT,
    QUEUE_ACT_RX24_CYLINDER_ARM_LEFT,
    QUEUE_ACT_RX24_CYLINDER_ARM_RIGHT,
	QUEUE_ACT_RX24_ORE_WALL,
    QUEUE_ACT_RX24_ORE_ROLLER_ARM,
    QUEUE_ACT_AX12_ROCKET,
	QUEUE_ACT_RX24_CYLINDER_COLOR_LEFT,
	QUEUE_ACT_RX24_CYLINDER_COLOR_RIGHT,
	QUEUE_ACT_AX12_CYLINDER_DISPOSE_LEFT,
	QUEUE_ACT_AX12_CYLINDER_DISPOSE_RIGHT,

	NB_ACT
} QUEUE_act_e;
