/*
 *  Club Robot ESEO 2008 - 2014
 *
 *  $Id$
 *
 *  Package : Carte Actionneur
 *  Description : Définition de types pour les variables globales
				définies specifiquement pour ce code.
 *  Auteur : Jacen
 */

typedef enum {
	QUEUE_ACT_RX24_FISH_MAGNETIC_ARM,
	QUEUE_ACT_RX24_FISH_UNSTICK_ARM,
	QUEUE_ACT_AX12_BLACK_SAND_CIRCLE,
	QUEUE_ACT_RX24_BOTTOM_DUNE_LEFT,
	QUEUE_ACT_RX24_BOTTOM_DUNE_RIGHT,
	QUEUE_ACT_RX24_MIDDLE_DUNE_LEFT,
	QUEUE_ACT_RX24_MIDDLE_DUNE_RIGHT,
	QUEUE_ACT_RX24_CONE_DUNE,
	QUEUE_ACT_RX24_DUNIX_LEFT,
	QUEUE_ACT_RX24_DUNIX_RIGHT,
	QUEUE_ACT_RX24_SAND_LOCKER_LEFT,
	QUEUE_ACT_RX24_SAND_LOCKER_RIGHT,
	QUEUE_ACT_RX24_SHIFT_CYLINDER,
	QUEUE_ACT_RX24_PENDULUM,
	QUEUE_ACT_POMPE_SAND_LOCKER_LEFT,
	QUEUE_ACT_POMPE_SAND_LOCKER_RIGHT,
	QUEUE_ACT_POMPE_BLACK_FRONT_LEFT,
	QUEUE_ACT_POMPE_BLACK_FRONT_RIGHT,
	QUEUE_ACT_POMPE_PENDULUM,
	NB_ACT
} QUEUE_act_e;
