/*
 * song_missionImpossible.c
 *
 * Created on: 02/19/2017
 */

#include "song_missionImpossible.h"

extern const MUSIC_PLAYER_note_t missionImpossibleData[75];

const MUSIC_PLAYER_songInfo_s missionImpossible = {
	.nbNotes = 75,
	.music = missionImpossibleData
};

const MUSIC_PLAYER_note_t missionImpossibleData[75] = {
	(MUSIC_PLAYER_note_t) {Eb6, 78},
	(MUSIC_PLAYER_note_t) {E6, 78},
	(MUSIC_PLAYER_note_t) {Eb6, 78},
	(MUSIC_PLAYER_note_t) {E6, 78},
	(MUSIC_PLAYER_note_t) {Eb6, 78},
	(MUSIC_PLAYER_note_t) {E6, 78},
	(MUSIC_PLAYER_note_t) {Eb6, 78},
	(MUSIC_PLAYER_note_t) {E6, 78},
	(MUSIC_PLAYER_note_t) {Eb6, 78},
	(MUSIC_PLAYER_note_t) {Eb6, 78},
	(MUSIC_PLAYER_note_t) {E6, 78},
	(MUSIC_PLAYER_note_t) {F6, 78},
	(MUSIC_PLAYER_note_t) {Gb6, 78},
	(MUSIC_PLAYER_note_t) {G6, 78},
	(MUSIC_PLAYER_note_t) {Ab6, 78},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {B6, 157},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {Db7, 360},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {Gb6, 157},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {G6, 157},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {B6, 157},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {Db7, 360},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {P, 315},
	(MUSIC_PLAYER_note_t) {Gb6, 157},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {G6, 157},
	(MUSIC_PLAYER_note_t) {P, 157},
	(MUSIC_PLAYER_note_t) {B6, 157},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {Eb6, 1262},
	(MUSIC_PLAYER_note_t) {P, 78},
	(MUSIC_PLAYER_note_t) {B6, 157},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {D6, 1262},
	(MUSIC_PLAYER_note_t) {P, 78},
	(MUSIC_PLAYER_note_t) {B6, 157},
	(MUSIC_PLAYER_note_t) {Ab6, 157},
	(MUSIC_PLAYER_note_t) {Db6, 1262},
	(MUSIC_PLAYER_note_t) {B6, 504},
	(MUSIC_PLAYER_note_t) {Db6, 315},
	(MUSIC_PLAYER_note_t) {P, 1262},
	(MUSIC_PLAYER_note_t) {P, 78},
	(MUSIC_PLAYER_note_t) {B6, 504},
	(MUSIC_PLAYER_note_t) {Ab6, 504},
	(MUSIC_PLAYER_note_t) {G6, 1262},
	(MUSIC_PLAYER_note_t) {P, 78},
	(MUSIC_PLAYER_note_t) {B6, 504},
	(MUSIC_PLAYER_note_t) {Ab6, 504},
	(MUSIC_PLAYER_note_t) {Gb6, 1262},
	(MUSIC_PLAYER_note_t) {P, 78},
	(MUSIC_PLAYER_note_t) {B6, 504},
	(MUSIC_PLAYER_note_t) {Ab6, 504},
	(MUSIC_PLAYER_note_t) {F6, 1262},
	(MUSIC_PLAYER_note_t) {E6, 157},
	(MUSIC_PLAYER_note_t) {Eb6, 315},
};
