/*
 *  Club Robot ESEO 2008 - 2014
 *
 *  $Id$
 *
 *  Package : Carte Actionneur
 *  Description : Définition de types pour les variables globales
				définies specifiquement pour ce code.
 *  Auteur : Jacen
 */

typedef enum {
	QUEUE_ACT_AX12_SMALL_BALL_BACK_LEFT,
	QUEUE_ACT_AX12_SMALL_BALL_BACK_RIGHT,
	QUEUE_ACT_AX12_SMALL_BALL_FRONT_LEFT,
	QUEUE_ACT_AX12_SMALL_BALL_FRONT_RIGHT,
	QUEUE_ACT_RX24_SMALL_CYLINDER_ARM,
	QUEUE_ACT_RX24_SMALL_CYLINDER_ELEVATOR,
	QUEUE_ACT_RX24_SMALL_CYLINDER_SLIDER,
	QUEUE_ACT_RX24_SMALL_CYLINDER_COLOR,
	QUEUE_ACT_AX12_SMALL_CYLINDER_DISPOSE,
	QUEUE_ACT_AX12_SMALL_CYLINDER_SLOPE,
	QUEUE_ACT_AX12_SMALL_CYLINDER_BALANCER,
	NB_ACT
} QUEUE_act_e;
